<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "bitcoin_user".
 *
 * @property int $id
 * @property string $login
 * @property string $apikey
 * @property string $secretkey
 * @property int $status
 * @property int $dt_add
 */
class BitcoinUser extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bitcoin_user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'dt_add'], 'integer'],
            [['login', 'apikey', 'secretkey'], 'string', 'max' => 255],
            [['balance'], 'double'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Login',
            'apikey' => 'Apikey',
            'secretkey' => 'Secretkey',
            'status' => 'Status',
            'balance' => 'Баланс',
            'dt_add' => 'Dt Add',
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if($this->dt_add !== null) {
            $this->dt_add = date('d-m-Y', $this->dt_add);
        }
    }
}
